pipeline{
    agent any

    stages{
        stage('Dev Deploy'){
            steps{
                withDockerRegistry( [ credentialsId: "ecr:us-east-1:aws-user", url: "https://590852515231.dkr.ecr.us-east-1.amazonaws.com" ] ){
                        sh 'docker rm -f spring-dev-env || true'
                        sh 'docker run -d -p 5000:8080 --name spring-dev-env 590852515231.dkr.ecr.us-east-1.amazonaws.com/sri-training-spring-app:latest'
                        sh 'echo Application running at port 5000 for dev environment'
                    }
            }

        }
        stage('Approval'){
             input{
                message  "Approve deployment to QA"
                ok "Allow"
            }
            steps{
                sh 'echo Approved Deployment to QA environment'
            }
        }
        stage('QA Deploy'){
            steps{

                sh 'docker rm -f spring-qa-env || true'
                sh 'docker run -d -p 5001:8080 --name spring-qa-env 590852515231.dkr.ecr.us-east-1.amazonaws.com/sri-training-spring-app:latest'
                sh 'echo Application running at port 5001 for QA environment'
            }
        }

        stage('Image Cleanup'){
            steps{
                sh 'docker container prune -f'
                sh 'docker image prune -f'
            }
        }
    }

}